name: movie
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  flutter_svg: ^1.0.3
  google_fonts: ^2.0.0

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/Brennan.jpg
    - assets/icons/

fonts:
  - family: Gordita
    fonts:
    - asset: assets/fonts/Gordita_Regular.otf
    - asset: assets/fonts/Gordita_Medium.otf
      weight: 500
    - asset: assets/fonts/Gordita_Bold.otf
      weight: 700
    - asset: assets/fonts/Gordita_Light.otf
      weight: 300
